### ISSUE TITLE
i18n plugin fail to load in latest aurelia framework 0.16.0 release

### ISSUE THREAD

**Issue by apDyn** [aurelia/i18n#10]
When starting the app, I get the following errors:
```
Unhandled promise rejection Error: Cannot read property 'querySelectorAll' of undefined
	Error loading http://localhost:54866/jspm_packages/github/aurelia/dialog@0.2.0/dialog.html!template-registry-entry
    at TemplateRegistryEntry.setTemplate (http://localhost:54866/jspm_packages/github/aurelia/loader@0.9.0/aurelia-loader.js:38:38)
    at http://localhost:54866/jspm_packages/github/aurelia/loader-default@0.10.0/aurelia-loader-default.js:22:15
    at run (http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:54866/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)
```
Please note, this is after manually altering the "github:aurelia/i18n@0.1.0" section in jspm's config.js to match the latest framework components.

**Comment by CharlesPockert** [comment]
Looks like this issue on aurelia-dialog to me - wrong repo :P https://github.com/aurelia/dialog/issues/25

**Comment by apDyn** [comment]
You're right.
Closing this issue.
