### ISSUE TITLE
Installing aurelia-i18n causes anchorIsContainer error during 

### ISSUE THREAD

**Issue by chiphart** [aurelia/i18n#179]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.48 

* **Browser:**
Chrome 54 | Firefox 50 

* **Language:**
TypeScript X.X

**Current behavior:**
Starting with the Aurelia typescript skeleton I can add i18next and the i18next-xhr-backend and things run fine. running typings on i18next and i18next-xhr-backend also things run fine. After installing aurelia-i18n using the jspm install aurelia-i18n command the following error appears in the javascript console:

 bluebird.min.js:31 Unhandled rejection TypeError: Cannot read property 'anchorIsContainer' of undefined
    at ViewCompiler.compile (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2542:106)
    at HtmlBehaviorResource.compile (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:3950:46)
    at ViewCompiler._compileElement (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2827:40)
    at ViewCompiler._compileNode (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2565:23)
    at ViewCompiler._compileElement (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2857:31)
    at ViewCompiler._compileNode (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2565:23)
    at ViewCompiler._compileElement (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2857:31)
    at ViewCompiler._compileNode (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2565:23)
    at ViewCompiler._compileElement (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2857:31)
    at ViewCompiler._compileNode (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2565:23)
    at ViewCompiler._compileNode (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2587:33)
    at ViewCompiler.compile (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:2534:12)
    at eval (http://local.tpa-assistant.com:9000/jspm_packages/npm/aurelia-templating@1.1.3/aurelia-templating.js:3192:50)
    at r (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
    at i._settlePromiseFromHandler (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
    at i._settlePromise (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13847)
    at i._settlePromise0 (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:14548)
    at i._settlePromises (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:15878)
    at r._drainQueue (http://local.tpa-assistant.com:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3148)D @ bluebird.min.js:31
browser-sync-client.js?v=2.18.2:2 GET http://local.tpa-assistant.com:9000/browser-sync/socket.io/?EIO=3&transport=polling&t=LZ6nvS0 net::ERR_CONNECTION_REFUSEDi.create @ browser-sync-client.js?v=2.18.2:2i @ browser-sync-client.js?v=2.18.2:2o.request @ browser-sync-client.js?v=2.18.2:2o.doPoll @ browser-sync-client.js?v=2.18.2:2n.poll @ browser-sync-client.js?v=2.18.2:2n.doOpen @ browser-sync-client.js?v=2.18.2:2n.open @ browser-sync-client.js?v=2.18.2:2n.open @ browser-sync-client.js?v=2.18.2:1n @ browser-sync-client.js?v=2.18.2:1n @ browser-sync-client.js?v=2.18.2:1n.open.n.connect @ browser-sync-client.js?v=2.18.2:1(anonymous function) @ browser-sync-client.js?v=2.18.2:1

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
Closing as duplicate. It's a regression in templating. Fix is going out today.

**Comment by chiphart** [comment]
Good to hear. Thanks.
