### ISSUE TITLE
Errors with aurelia pre-beta release

### ISSUE THREAD

**Issue by heruan** [aurelia/i18n#29]
After upgrading to Aurelia pre-beta release, I get this error on plugin initialization:
```
Unhandled promise rejection TypeError: resources.getAttribute is not a function
    at http://localhost:9000/jspm/github/aurelia/i18n@0.3.0/index.js:87:44
    at next (http://localhost:9000/jspm/github/aurelia/framework@0.18.0/aurelia-framework.js:19:32)
    at run (http://localhost:9000/jspm/npm/core-js@1.2.6/modules/es6.promise.js:107:49)
    at http://localhost:9000/jspm/npm/core-js@1.2.6/modules/es6.promise.js:121:9
    at MutationObserver.flush (http://localhost:9000/jspm/npm/core-js@1.2.6/modules/$.microtask.js:25:7)(anonymous function) @ es6.promise.js:138
es6.promise.js:138 Unhandled promise rejection TypeError: resources.getAttribute is not a function
    at http://localhost:9000/jspm/github/aurelia/i18n@0.3.0/index.js:87:44
    at next (http://localhost:9000/jspm/github/aurelia/framework@0.18.0/aurelia-framework.js:19:32)
    at run (http://localhost:9000/jspm/npm/core-js@1.2.6/modules/es6.promise.js:107:49)
    at http://localhost:9000/jspm/npm/core-js@1.2.6/modules/es6.promise.js:121:9
    at MutationObserver.flush (http://localhost:9000/jspm/npm/core-js@1.2.6/modules/$.microtask.js:25:7)(anonymous function) @ es6.promise.js:138
```
referring to the `getAttribute` method here:
```javascript
    frameworkConfig.postTask(function () {
      var resources = frameworkConfig.container.get(_aureliaTemplating.ViewResources);
      var htmlBehaviorResource = resources.getAttribute('t');
      // ...
```

**Comment by zewa666** [comment]
Thanks for the report and thanks @JeroenVinke for your quick help. As @EisenbergEffect said, the API will be made public again. That should fix the issue

**Comment by EisenbergEffect** [comment]
Released fix to templating.

**Comment by EisenbergEffect** [comment]
@zewa666 On an unrelated note. Now that the binding engine has signals, that's probably something you should take advantage of in the i18n library to refresh all translated values when a culture change happens.
