### ISSUE TITLE
Intl and i18next not found doing jspm update

### ISSUE THREAD

**Issue by salminio** [aurelia/i18n#64]
We have one of our jspm dependencies on aurelia-i18n
`      "aurelia-i18n": "npm:aurelia-i18n@^0.4.1",`

today it pulled down version 0.4.8 and the .jspm.json had both Intl and i18next without github prefixes and "registry": "npm". 

causing the following errors:
```
warn Error on lookup for github:i18next/i18next@^1.9.0, retrying (1).
     Error: fatal: unable to access 'i18next/i18next@1.9.0.git/': The requested URL returned error: 400
warn Error on lookup for github:andyearnshaw/Intl.js@^0.1.4, retrying (1).
     Error: fatal: unable to access 'andyearnshaw/Intl.js@0.1.4.git/': The requested URL returned error: 400
```

as a test removing the registry entry (both of them) from .jspm.json fixed my issue. As best I can tell - without using the specific registry prefix it will use the value of the registry set by the registry property in the package.json. I don't think either of those packages are registered with npm or jspm? Maybe that's the issue. Locking into 4.6 for now.

One other weird thing was the listing in .jspm.json for those entries looks like the below - has an extra @* at the end
```
 "dependencies": {
    "Intl.js": "github:andyearnshaw/Intl.js@^0.1.4@*",
    "i18next": "github:i18next/i18next@^1.9.0@*",
    "aurelia-binding": "aurelia-binding@^1.0.0-beta.1.1.0",
    "aurelia-dependency-injection": "aurelia-dependency-injection@^1.0.0-beta.1.1.2",
    "aurelia-event-aggregator": "aurelia-event-aggregator@^1.0.0-beta.1.1.0",
    "aurelia-loader-default": "aurelia-loader-default@^1.0.0-beta.1.1.1",
    "aurelia-pal": "aurelia-pal@^1.0.0-beta.1.1.1",
    "aurelia-templating": "aurelia-templating@^1.0.0-beta.1.1.0",
    "aurelia-templating-resources": "aurelia-templating-resources@^1.0.0-beta.1.1.0"
  }
```

**Comment by flieks** [comment]
i also have this problem when jspm install aurelia-i18n
Repo npm:i18next/i18next not found!

**Comment by doktordirk** [comment]
+1

**Comment by Exsilium122** [comment]
I have done pull request to jspm to add those libraries to dependencies. Please vote: https://github.com/jspm/registry/pull/737

**Comment by doktordirk** [comment]
@flieks try in console
```
npm prune && npm install jspm@0.16.15 && jspm install && npm uninstall jspm
```

**Comment by doktordirk** [comment]
@salminio for jspm update try
```
npm prune && npm install jspm@0.16.15 && jspm update && npm uninstall jspm
```

**Comment by salminio** [comment]
Ran that command but still getting the same error

**Comment by doktordirk** [comment]
@salminio
was on of the tries that worked for me. currently i just install and keep jspm@0.16.15 locally. in case of problems i clear out previous jspm packges. so:

npm install --save jspm@0.16.15
del -rf jspm_packages (or so)
remove the map entry in config.js
jspm install

**Comment by salminio** [comment]
that worked.

**Comment by ehudkaldor** [comment]
none of these worked for me. any other workaround/solution?

**Comment by heruan** [comment]
I reverted to `jspm` v0.16.15 (why can't we use the latest version?) and `jspm update` went fine, but now my application runs only on Chrome, and I get this on Safari:
```
Failed to load resource: /dist/Intl.js (Not Found)
```
and in Firefox a generic
```
uncaught exception: [object Object] <unknown>
```
What happened to Aurelia/JSPM with the latest updates?

**Comment by EisenbergEffect** [comment]
The jspm team gave us bad info on how to update to be compatible with prvious and next versions. So, they broke our stuff. Then we had to lock down versions to get it to work. We've since updated our libraries and everything should be fixed again so you can update your jspm and then jspm update Aurelia.

**Comment by heruan** [comment]
Sure I'm missing something… but
```
$ jspm install aurelia-i18n
     Updating registry cache...
     Looking up npm:aurelia-i18n
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-templating
     Looking up npm:aurelia-templating-resources
     Looking up npm:i18next/i18next
     Looking up npm:intl
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-task-queue
     Looking up npm:core-js
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-path

err  Repo npm:i18next/i18next not found!

warn Installation changes not saved.

$ jspm --version
0.16.27
```

**Comment by ehudkaldor** [comment]
Yup, same here.

**Comment by RWOverdijk** [comment]
:+1:

**Comment by henning-krause** [comment]
Same here. Uninstalled aurelia-i18n, ran jspm update.Then tried to install it again, and it failed:

warn Repo npm:i18next/i18next not found!
err  Repo npm:i18next/i18next not found!

**Comment by doktordirk** [comment]
try
## Rebuild your project
Rebuilding your project as follows can help. Currently, a local installation of jspm@0.16.15 (`npm install jspm@0.16.15 --save`) is advised.
* `npm prune`
* `npm install`
* delete the jspm_packages folder `rm -rf ./jspm_packages`
* delete the map entry in `config.json`
* `jspm install`

**Comment by RWOverdijk** [comment]
Adding `npm:` works for me (as a workaround).

`jspm i npm:aurelia-i18n`

**Comment by henning-krause** [comment]
@doktordirk , thanks, that did the trick.

**Comment by droda59** [comment]
@ehudkaldor, were you able to fix it? I still can't

**Comment by ehudkaldor** [comment]
still not working for me....
NODEJS 5.7.0, all the others are default (npm install and jspm install with no version param).

**Comment by henning-krause** [comment]
@ehudkaldor , have you tried the steps outlined by @doktordirk? You have to follow them exactly. That helped me. Especially important is the 

npm install jspm@0.16.15  --save (or --save-dev, depending on your setup).

**Comment by ehudkaldor** [comment]
it did not work. (long) printout below:

```
~/ehu # npm prune && npm install && rm -rf ./jspm_packages && npm install --save jspm@0.16.15 aurelia-bundler aurelia-tools babel del vinyl-paths require-dir  run-sequence  conv
entional-changelog  browser-sync  karma karma-babel-preprocessor karma-chrome-launcher karma-coverage  karma-jasmine karma-jspm gulp-bump gulp-yuidoc gulp-eslint gulp-protractor
 gulp-changed gulp-babel gulp-sourcemaps object.assign gulp-notify gulp-plumber
npm WARN package.json appname@0.0.1 No repository field.
npm WARN package.json appname@0.0.1 No README data
npm WARN package.json appname@0.0.1 No license field.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN appname@0.0.1 No repository field.
npm WARN appname@0.0.1 No license field.
npm WARN deprecated babel-core@5.8.3: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
appname@0.0.1 /root/ehu
+-- aurelia-bundler@0.3.2
| +-- html-minifier@1.2.0
| | `-- uglify-js@2.6.2
| |   +-- async@0.2.10 
| |   +-- source-map@0.5.3 
| |   `-- yargs@3.10.0
| |     `-- window-size@0.1.0 
| `-- systemjs-builder@0.15.10
|   +-- bluebird@3.3.3 
|   +-- glob@6.0.4 
|   +-- source-map@0.5.3 
|   `-- traceur@0.0.102
|     +-- commander@2.6.0 
|     `-- glob@4.3.5 
+-- conventional-changelog@1.1.0
| `-- conventional-changelog-core@1.3.0
|   +-- conventional-changelog-writer@1.1.1
|   | `-- semver@5.1.0 
|   `-- git-semver-tags@1.1.2
|     `-- semver@5.1.0 
+-- del@2.2.0
| `-- globby@4.0.0
|   `-- glob@6.0.4 
+-- gulp-babel@6.1.2
| +-- babel-core@6.6.4
| | +-- babel-generator@6.6.4
| | | `-- source-map@0.5.3 
| | +-- babel-register@6.6.0
| | | `-- babel-core@6.6.4
| | |   `-- source-map@0.5.3 
| | `-- source-map@0.5.3 
| `-- vinyl-sourcemaps-apply@0.2.1
|   `-- source-map@0.5.3 
+-- gulp-bump@1.0.0
| +-- semver@5.1.0 
| `-- through2@0.5.1
|   `-- readable-stream@1.0.33 
+-- gulp-eslint@2.0.0
| `-- eslint@2.2.0
|   +-- glob@6.0.4 
|   `-- table@3.7.8
|     `-- bluebird@3.3.3 
+-- gulp-notify@2.2.0
| +-- node-notifier@4.5.0
| | `-- semver@5.1.0 
| `-- through2@0.6.5
|   `-- readable-stream@1.0.33 
+-- gulp-protractor@2.1.0
| `-- protractor@3.0.0
|   `-- request@2.57.0
|     +-- aws-sign2@0.5.0 
|     +-- bl@0.9.5 
|     | `-- readable-stream@1.0.33 
|     +-- caseless@0.10.0 
|     +-- form-data@0.2.0 
|     | +-- async@0.9.2 
|     | `-- combined-stream@0.0.7 
|     |   `-- delayed-stream@0.0.5 
|     +-- har-validator@1.8.0 
|     +-- hawk@2.3.1 
|     +-- mime-types@2.0.14 
|     | `-- mime-db@1.12.0 
|     `-- qs@3.1.0 
+-- gulp-yuidoc@0.1.2
| +-- through2@0.4.1
| | +-- readable-stream@1.0.33 
| | `-- xtend@2.1.2
| |   `-- object-keys@0.4.0 
| +-- vinyl-fs@0.1.4
| | `-- glob-stream@3.1.18
| |   +-- glob@4.5.3 
| |   `-- through2@0.6.5
| |     `-- readable-stream@1.0.33 
| `-- yuidocjs@0.3.50
|   `-- yui@3.14.1
|     `-- request@2.21.0
|       +-- forever-agent@0.5.2 
|       `-- form-data@0.0.8
|         +-- async@0.2.10 
|         `-- combined-stream@0.0.7 
|           `-- delayed-stream@0.0.5 
+-- jspm@0.16.15 
| +-- graceful-fs@3.0.8 
| +-- jspm-github@0.13.11 
| | +-- expand-tilde@1.2.0 
| | +-- graceful-fs@3.0.8 
| | +-- netrc@0.1.4 
| | +-- request@2.53.0 
| | | +-- aws-sign2@0.5.0 
| | | +-- bl@0.9.5 
| | | | `-- readable-stream@1.0.33 
| | | +-- caseless@0.9.0 
| | | +-- combined-stream@0.0.7 
| | | | `-- delayed-stream@0.0.5 
| | | +-- forever-agent@0.5.2 
| | | +-- form-data@0.2.0 
| | | | `-- async@0.9.2 
| | | +-- hawk@2.3.1 
| | | +-- http-signature@0.10.1 
| | | +-- mime-types@2.0.14 
| | | | `-- mime-db@1.12.0 
| | | +-- oauth-sign@0.6.0 
| | | `-- qs@2.3.3 
| | +-- rimraf@2.3.4 
| | | `-- glob@4.5.3 
| | +-- semver@5.1.0 
| | +-- tar@2.2.1 
| | | +-- block-stream@0.0.8 
| | | `-- fstream@1.0.8 
| | `-- yauzl@2.4.1 
| |   `-- fd-slicer@1.0.1 
| |     `-- pend@1.2.0 
| +-- jspm-npm@0.25.3 
| | +-- graceful-fs@3.0.8 
| | +-- request@2.58.0 
| | | +-- aws-sign2@0.5.0 
| | | +-- bl@0.9.5 
| | | | `-- readable-stream@1.0.33 
| | | +-- caseless@0.10.0 
| | | +-- extend@2.0.1 
| | | +-- har-validator@1.8.0 
| | | +-- hawk@2.3.1 
| | | +-- mime-types@2.0.14 
| | | | `-- mime-db@1.12.0 
| | | `-- qs@3.1.0 
| | +-- rmdir@1.1.0 
| | | `-- node.flow@1.2.3 
| | |   `-- node.extend@1.0.8 
| | |     +-- is@0.2.7 
| | |     `-- object-keys@0.4.0 
| | +-- semver@5.1.0 
| | +-- systemjs-builder@0.14.15 
| | | +-- bluebird@3.3.3 
| | | +-- glob@6.0.4 
| | | +-- source-map@0.5.3 
| | | +-- systemjs@0.19.9 
| | | `-- traceur@0.0.93 
| | |   +-- commander@2.6.0 
| | |   +-- glob@4.3.5 
| | |   `-- semver@2.3.2 
| | `-- tar@1.0.3 
| +-- jspm-registry@0.4.0 
| | +-- graceful-fs@3.0.8 
| | `-- semver@4.3.6 
| +-- liftoff@2.2.0 
| | +-- extend@2.0.1 
| | +-- findup-sync@0.3.0 
| | +-- flagged-respawn@0.3.1 
| | `-- rechoir@0.6.2 
| +-- ncp@2.0.0 
| +-- semver@5.1.0 
| +-- systemjs@0.19.6 
| +-- systemjs-builder@0.14.11 
| +-- traceur@0.0.92 
| | +-- commander@2.6.0 
| | +-- glob@4.3.5 
| | `-- semver@2.3.2 
| `-- uglify-js@2.4.24 
|   +-- async@0.2.10 
|   +-- source-map@0.1.34 
|   `-- yargs@3.5.4 
|     `-- window-size@0.1.0 
+-- karma@0.13.21
| +-- log4js@0.6.32
| | +-- readable-stream@1.0.33 
| | `-- semver@4.3.6 
| +-- socket.io@1.4.5
| | `-- engine.io@1.6.8
| |   `-- accepts@1.1.4
| |     `-- mime-types@2.0.14 
| |       `-- mime-db@1.12.0 
| `-- source-map@0.5.3 
+-- karma-babel-preprocessor@6.0.1
| `-- babel-core@6.6.4
|   `-- source-map@0.5.3 
`-- karma-coverage@0.5.4
  `-- source-map@0.5.3 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN appname@0.0.1 No repository field.
npm WARN appname@0.0.1 No license field.
~/ehu # jspm -v
0.16.15
Running against local jspm install.
~/ehu # npm prune && npm install && rm -rf ./jspm_packages && jspm cache-clear && jspm update && jspm install -y && jspm install -y aurelia-bootstrapper aurelia-framework aureli
a-logging-console aurelia-fetch-client aurelia-history-browser aurelia-loader-default aurelia-router aurelia-templating-binding aurelia-templating-resources aurelia-templating-r
outer aurelia-i18n aurelia-animator-css semantic-ui font-awesome fetch text
npm WARN package.json appname@0.0.1 No repository field.
npm WARN package.json appname@0.0.1 No README data
npm WARN package.json appname@0.0.1 No license field.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN appname@0.0.1 No repository field.
npm WARN appname@0.0.1 No license field.
ok   Loader file cache cleared.
ok   Package cache cleared.
ok   github cache cleared.
ok   jspm cache cleared.
ok   npm cache cleared.

warn All caches cleared.
     Please post an issue if you suspect the cache isn't invalidating properly.
     jspm install -f is equivalent to running a cache clear for that specific package tree.
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Creating registry cache...
     Downloading npm:core-js@1.2.6
     Downloading npm:babel-core@5.8.35
     Downloading npm:babel-runtime@5.8.35
ok   Installed babel as npm:babel-core@^5.8.24 (5.8.35)
     Looking up github:jspm/nodelibs-process
     Looking up npm:path-browserify
     Looking up npm:util
     Downloading npm:util@0.10.3
     Downloading npm:path-browserify@0.0.0
     Downloading github:jspm/nodelibs-process@0.1.2
     Looking up github:jspm/nodelibs-path
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-fs
     Looking up npm:process
     Downloading npm:process@0.11.2
ok   Installed npm:process@^0.11.0 (0.11.2)
     Downloading github:jspm/nodelibs-path@0.1.0
     Downloading github:systemjs/plugin-json@0.1.0
     Downloading github:jspm/nodelibs-fs@0.1.2
     Looking up github:jspm/nodelibs-assert
ok   Installed npm:path-browserify@0.0.0 (0.0.0)
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.2)
     Downloading github:jspm/nodelibs-assert@0.1.0
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
     Looking up npm:assert
ok   Installed github:jspm/nodelibs-path@^0.1.0 (0.1.0)
     Downloading npm:assert@1.3.0
     Looking up github:jspm/nodelibs-util
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed npm:assert@^1.3.0 (1.3.0)
     Downloading github:jspm/nodelibs-util@0.1.0
ok   Installed github:jspm/nodelibs-assert@^0.1.0 (0.1.0)
ok   Installed npm:util@0.10.3 (0.10.3)
     Looking up npm:inherits
     Downloading npm:inherits@2.0.1
ok   Installed npm:inherits@2.0.1 (2.0.1)
ok   Installed github:jspm/nodelibs-util@^0.1.0 (0.1.0)
ok   Installed babel-runtime as npm:babel-runtime@^5.8.24 (5.8.35)
ok   Installed core-js as npm:core-js@^1.1.4 (1.2.6)
ok   Install tree has no forks.
     Looking up loader files...
       system.js
       system.js.map
       system-csp-production.js
       system.src.js
       system-csp-production.js.map
       system-polyfills.js
       system-csp-production.src.js
       system-polyfills.js.map
       system-polyfills.src.js
     
     Using loader versions:
       systemjs@0.19.6
ok   Loader files downloaded successfully

ok   Install complete.
     Looking up npm:babel-core
     Looking up npm:core-js
     Looking up npm:babel-runtime
     Updating registry cache...
ok   Up to date - babel as npm:babel-core@^5.8.24 (5.8.35)
     Looking up github:jspm/nodelibs-fs
     Looking up github:jspm/nodelibs-path
     Looking up github:jspm/nodelibs-process
     Looking up github:systemjs/plugin-json
     Looking up npm:process
     Looking up npm:path-browserify
     Looking up github:jspm/nodelibs-assert
     Looking up npm:assert
     Looking up npm:util
     Looking up npm:inherits
     Looking up github:jspm/nodelibs-util
ok   Up to date - core-js as npm:core-js@^1.1.4 (1.2.6)
ok   Up to date - babel-runtime as npm:babel-runtime@^5.8.24 (5.8.35)
ok   Install tree has no forks.

ok   Install complete.
     Updating registry cache...
     Looking up npm:aurelia-bootstrapper
     Looking up npm:aurelia-framework
     Looking up npm:aurelia-logging-console
     Looking up npm:aurelia-fetch-client
     Looking up npm:aurelia-history-browser
     Looking up npm:aurelia-loader-default
     Looking up npm:aurelia-router
     Looking up npm:aurelia-templating-binding
     Looking up npm:aurelia-templating-resources
     Looking up npm:aurelia-templating-router
     Looking up npm:aurelia-i18n
     Looking up npm:aurelia-animator-css
     Looking up npm:font-awesome
     Downloading npm:aurelia-templating-resources@1.0.0-beta.1.1.2
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-path
     Looking up npm:aurelia-task-queue
     Looking up npm:aurelia-templating
     Downloading npm:aurelia-logging-console@1.0.0-beta.1.1.4
     Downloading npm:aurelia-templating-binding@1.0.0-beta.1.1.2
     Downloading npm:aurelia-router@1.0.0-beta.1.1.3
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-history
     Looking up npm:aurelia-route-recognizer
     Downloading npm:aurelia-history-browser@1.0.0-beta.1.1.4
     Downloading npm:aurelia-fetch-client@1.0.0-beta.1.1.1
     Downloading npm:aurelia-animator-css@1.0.0-beta.1.1.2
     Looking up npm:aurelia-metadata
     Downloading npm:aurelia-templating-router@1.0.0-beta.1.1.2
     Downloading npm:aurelia-loader-default@1.0.0-beta.1.1.3
     Downloading npm:aurelia-framework@1.0.0-beta.1.1.4
     Downloading npm:aurelia-bootstrapper@1.0.0-beta.1.1.4
     Looking up npm:aurelia-pal-browser
     Looking up npm:aurelia-polyfills
     Downloading npm:aurelia-loader@1.0.0-beta.1.1.1
     Downloading npm:aurelia-task-queue@1.0.0-beta.1.1.1
     Downloading npm:aurelia-logging@1.0.0-beta.1.1.2
     Downloading npm:aurelia-pal@1.0.0-beta.1.1.1
     Downloading npm:aurelia-path@1.0.0-beta.1.1.1
     Downloading npm:aurelia-binding@1.0.0-beta.1.2.2
     Downloading npm:aurelia-templating@1.0.0-beta.1.1.2
     Downloading npm:aurelia-dependency-injection@1.0.0-beta.1.1.4
     Downloading npm:font-awesome@4.5.0
     Downloading npm:aurelia-history@1.0.0-beta.1.1.1
     Downloading npm:aurelia-event-aggregator@1.0.0-beta.1.1.1
     Downloading npm:aurelia-metadata@1.0.0-beta.1.1.6
     Downloading npm:aurelia-route-recognizer@1.0.0-beta.1.1.3
     Downloading npm:aurelia-pal-browser@1.0.0-beta.1.1.4
     Downloading npm:aurelia-i18n@0.4.13
     Looking up npm:intl
     Downloading npm:aurelia-polyfills@1.0.0-beta.1.0.1
     Looking up github:systemjs/plugin-text
     Looking up github:Semantic-Org/Semantic-UI
     Looking up github:github/fetch
     Downloading npm:intl@1.1.0
     Looking up github:systemjs/plugin-css
     Looking up github:i18next/i18next@^1.9.0
     Downloading github:systemjs/plugin-text@0.0.7
     Downloading github:github/fetch@0.11.0
     Downloading github:Semantic-Org/Semantic-UI@2.1.8

warn Error on lookup for github:i18next/i18next@^1.9.0, retrying (1).
     Error: fatal: unable to access 'i18next/i18next@^1.9.0.git/': The requested URL returned error: 400

     Downloading github:systemjs/plugin-css@0.1.20

warn Error on lookup for github:i18next/i18next@^1.9.0, retrying (2).
     Error: fatal: unable to access 'i18next/i18next@^1.9.0.git/': The requested URL returned error: 400

ok   Installed npm:aurelia-history@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.1)
     Looking up github:components/jquery
ok   Installed npm:aurelia-logging-console@^1.0.0-beta.1.1.3 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-pal@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.1)
ok   Installed npm:aurelia-logging@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.2)
ok   Installed aurelia-logging-console as npm:aurelia-logging-console@^1.0.0-beta.1.1.4 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-task-queue@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.1)

warn Error on lookup for github:i18next/i18next@^1.9.0, retrying (3).
     Error: fatal: unable to access 'i18next/i18next@^1.9.0.git/': The requested URL returned error: 400

ok   Installed npm:aurelia-path@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.1)
ok   Installed npm:aurelia-event-aggregator@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.1)
ok   Installed npm:aurelia-polyfills@^1.0.0-beta.1.0.0 (1.0.0-beta.1.0.1)
ok   Installed npm:aurelia-loader-default@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.3)
ok   Installed npm:aurelia-loader@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.1)
ok   Installed npm:aurelia-templating-binding@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.2)
ok   Installed npm:aurelia-pal-browser@^1.0.0-beta.1.1.2 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-dependency-injection@^1.0.0-beta.1.1.2 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-dependency-injection@^1.0.0-beta.1.1.4 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-history-browser@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.4)
ok   Installed aurelia-history-browser as npm:aurelia-history-browser@^1.0.0-beta.1.1.4 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-framework@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.4)
ok   Installed npm:aurelia-metadata@^1.0.0-beta.1.1.3 (1.0.0-beta.1.1.6)
ok   Installed aurelia-loader-default as npm:aurelia-loader-default@^1.0.0-beta.1.1.3 (1.0.0-beta.1.1.3)
ok   Installed npm:aurelia-templating-router@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.2)
     Downloading github:components/jquery@2.2.1
ok   Installed text as github:systemjs/plugin-text@^0.0.7 (0.0.7)

warn Error on lookup for github:i18next/i18next@^1.9.0
     Error: fatal: unable to access 'i18next/i18next@^1.9.0.git/': The requested URL returned error: 400


err  Error: Error looking up github:i18next/i18next@^1.9.0.
         at /root/ehu/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (/root/ehu/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/root/ehu/node_modules/rsvp/dist/rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)
ok   Installed npm:aurelia-route-recognizer@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.3)
ok   Installed aurelia-fetch-client as npm:aurelia-fetch-client@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.1)
ok   Installed github:systemjs/plugin-css@0.1 (0.1.20)
ok   Installed github:systemjs/plugin-css (0.1.20)
ok   Installed font-awesome as npm:font-awesome@^4.5.0 (4.5.0)
ok   Installed npm:aurelia-router@^1.0.0-beta.1.1.0 (1.0.0-beta.1.1.3)
ok   Installed aurelia-router as npm:aurelia-router@^1.0.0-beta.1.1.3 (1.0.0-beta.1.1.3)
ok   Installed fetch as github:github/fetch@^0.11.0 (0.11.0)

err  Error looking up github:i18next/i18next@^1.9.0.

warn Installation changes not saved.

```

**Comment by doktordirk** [comment]
did you delete the map entry in config.json  ? (in case you didn't and retry delete the jspm folder again)

**Comment by khenderick** [comment]
This is so annoying. Every few days something is somehow broken :(. And unfortunately, the above suggested solution didn't work.

**Comment by EisenbergEffect** [comment]
@khenderick We sincerely apologize. JSPM/SystemJS has turned out to be pretty unstable. @zewa666 Can you assist?

**Comment by zewa666** [comment]
For JSPM 0.16.15 everything should be fixed, for newer versions we still experience issues related to Github installs, which result from using the old version of i18next. Will try to update it this week than all issues should be passé.

**Comment by khenderick** [comment]
@EisenbergEffect, I understand as we're still in a beta now, but it's something we definitely need to have ironed out once we move towards further releases. Where the old-style frameworks are a matter of reading the changelog and throwing a few files over, the current jspm/npm style installing is so much more complex that we must be able to completely rely on it working correctly.

It it at least something we want to have fixed as soon as possible, together with "how to update in 3 easy steps"-style documentation. I'm working on a new generation of a product and decided to use Aurelia over the well known Durandal, and getting stuck during development is not good.

But again, @EisenbergEffect it's not shooting, just outing concerns. I truly want to use this (as I fell in love with Durandal), but I can imagine people abandon using the project when they "get stuck".

**Comment by Gheoan** [comment]
One solution would be to lock down jspm/systemjs/systemjs builder version across repos and documentation.

**Comment by EisenbergEffect** [comment]
Believe me, we share your concerns. We have locked down the versions in the skeletons, I believe. However, that was done more recently...

**Comment by khenderick** [comment]
What's actually the status of this ticket? It's closed but it seems some people (besides me) are not able to get everything up and running again. I decided to set up a new Aurelia env from scratch and after extracting the ```aurelia-skeleton-navigation``` (```1.1.5```), running ```npm install``` and ```jspm install -y```, it still is impossible to ```jspm install aurelia-i18n```.

```
warn Error on lookup for github:i18next/i18next@^1.9.0
     Error: fatal: unable to access 'i18next/i18next@^1.9.0.git/': The requested URL returned error: 400


err  Error looking up github:i18next/i18next@^1.9.0.
```

**Comment by EisenbergEffect** [comment]
@zewa666 Can you explain what is going on with this?

**Comment by doktordirk** [comment]
@khenderick that happens (for some to me unknown reason) if the jspm folder isn't cleared. following should work

(if you used a local install of eg jspm 0.16.30, just delete the whole npm folder do be double save first)
npm install jspm@0.16.15
delete jspm folder
delete map entry in config.js
then jspm install

**Comment by zewa666** [comment]
@doktordirk thanks for clarifying it again. Yep as always if you experience some weird issues with JSPM it helps to delete the complete jspm folder and the map entries. Then install again. :+1:

**Comment by doktordirk** [comment]
@khenderick 
the order i thing would be (if applicable)
npm install --save-dev jspm@0,16,15
aurelia-update
delete jspm folder 
delete map entry
jspm install (since aurelia-update already fixed your package.json, jspm update not needed i this case)

i know it can be annoying to jspm update these days, but rest assured, it still works the ways desciibed

**Comment by doktordirk** [comment]
@khenderick that css.js comes from dialog? never seen the solution but i still guess either
* jspm install css --dev
or
* jspm uninstall css --dev

**Comment by khenderick** [comment]
The jspm install css --dev did the trick apparently. Nice. Thanks again for the help @doktordirk
